//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class ReportPrintingOptions : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReportPrintingOptions defaultInstance = ((ReportPrintingOptions)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReportPrintingOptions())));
        
        public static ReportPrintingOptions Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideNormalRange {
            get {
                return ((bool)(this["HideNormalRange"]));
            }
            set {
                this["HideNormalRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGroupTitle {
            get {
                return ((bool)(this["ShowGroupTitle"]));
            }
            set {
                this["ShowGroupTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTestTitle {
            get {
                return ((bool)(this["ShowTestTitle"]));
            }
            set {
                this["ShowTestTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncudeDigitalSignature {
            get {
                return ((bool)(this["IncudeDigitalSignature"]));
            }
            set {
                this["IncudeDigitalSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LetterHead {
            get {
                return ((bool)(this["LetterHead"]));
            }
            set {
                this["LetterHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlankLetterHead {
            get {
                return ((bool)(this["BlankLetterHead"]));
            }
            set {
                this["BlankLetterHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAddressInEnvelope {
            get {
                return ((bool)(this["ShowAddressInEnvelope"]));
            }
            set {
                this["ShowAddressInEnvelope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergeAllTestGroups {
            get {
                return ((bool)(this["MergeAllTestGroups"]));
            }
            set {
                this["MergeAllTestGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergeSingleTestGroup {
            get {
                return ((bool)(this["MergeSingleTestGroup"]));
            }
            set {
                this["MergeSingleTestGroup"] = value;
            }
        }
    }
}
